# Generated by Django 3.0.2 on 2020-01-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('birth_year', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
