# Generated by Django 3.0.2 on 2020-01-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200128_1332'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
